services:
  - type: web
    name: n8n
    env: docker
    plan: free
    dockerfilePath: ./docker/images/n8n/Dockerfile
    startCommand: ""  # Optional: You can leave blank if CMD is in Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: changeme
      - key: WEBHOOK_URL
        value: https://n8n-7ob.onrender.com
